### PR TITLE
fix build on osx

### LINKED ISSUE #693: Build error generated mac el capitan
`/Users/zarboz/hyperion/libsrc/utils/Logger.cpp:49:25: error: use of undeclared identifier 'program_invocation_short_name'
        _appname = std::string(program_invocation_short_name);
                               ^
/Users/zarboz/hyperion/libsrc/utils/Logger.cpp:61:12: error: use of undeclared identifier 'program_invocation_short_name'
                openlog (program_invocation_short_name, LOG_CONS | LOG_PID | LOG_NDELAY, LOG_LOCAL0);
                         ^
2 errors generated.
`

### PR DESCRIPTION
**Pull request by redPanther**
fix #693

### CODE REVIEW

File: libsrc/utils/Logger.cpp [hunk 1]
```diff
@@ -46,7 +46,11 @@ Logger::Logger ( std::string name, LogLevel minLevel ):
 	_syslogEnabled(true),
 	_loggerId(loggerId++)
 {
+#ifdef GLIBC
```
Comment (lrusak) [inline libsrc/utils/Logger.cpp]: shouldn't this be `__GLIBC__` ?

**Comment by redPanther** [comment]
fixed in my pending PR
